# Generated by Django 4.2.3 on 2023-10-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('x_coordinate', models.DecimalField(decimal_places=9, max_digits=15)),
                ('y_coordinate', models.DecimalField(decimal_places=9, max_digits=15)),
                ('full_address', models.CharField(blank=True, max_length=100, null=True)),
                ('road_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantServiceName',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantVideo',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=255)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_videos', to='app_model.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menus', to='app_model.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantAdditionalInfo',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_info', to='app_model.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_model.restaurantservicename'),
        ),
    ]
