# Generated by Django 4.2.3 on 2023-10-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_model', '0003_alter_restaurant_full_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantservicename',
            name='is_use',
            field=models.BooleanField(default=False),
        ),
    ]
