# Generated by Django 4.2.1 on 2023-10-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_model", "0002_alter_restaurant_full_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="full_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="road_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
